/*
ATBM-CQ-07
*/

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-----------Table --------------

CREATE TABLE NHANSU (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(10),
    NGSINH DATE,
    PHUCAP INT,
    DT VARCHAR2(10),
    VAITRO NVARCHAR2(20),
    MADV VARCHAR2(10)
);

CREATE TABLE SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(10),
    NGSINH DATE,
    DCHI NVARCHAR2(100),
    DT VARCHAR2(10),
    MACT VARCHAR2(10),
    MANGANH VARCHAR2(10),
    SOTCTL INT,
    DTBTL NUMBER
);

CREATE TABLE DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV NVARCHAR2(50),
    TRGDV VARCHAR2(10)
);

CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP NVARCHAR2(80),
    SOTC INT,
    STLT INT,
    STTH INT,
    SOSVTD INT,
    MADV VARCHAR2(10)
);


CREATE TABLE KHMO (
    MAHP VARCHAR2(10),
    HK INT,
    NAM INT,
    MACT VARCHAR2(10),
    PRIMARY KEY(MAHP, HK, NAM, MACT)
);


CREATE TABLE PHANCONG (
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK INT,
    NAM INT,
    MACT VARCHAR2(10),
    PRIMARY KEY(MAGV, MAHP, HK, NAM, MACT)
);


CREATE TABLE DANGKY (
    MASV VARCHAR2(10),
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK INT,
    NAM INT,
    MACT VARCHAR2(10),
    DIEMTH NUMBER, 
    DIEMQT NUMBER, 
    DIEMCK NUMBER,
    DIEMTK NUMBER,
    PRIMARY KEY(MASV, MAGV, MAHP, HK, NAM, MACT)
);


ALTER TABLE NHANSU
ADD CONSTRAINT FK_NHANSU_DONVI
FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

ALTER TABLE DONVI
ADD CONSTRAINT FK_DONVI_NHANSU
FOREIGN KEY (TRGDV) REFERENCES NHANSU(MANV);

ALTER TABLE HOCPHAN
ADD CONSTRAINT FK_HOCPHAN_DONVI
FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

ALTER TABLE KHMO
ADD CONSTRAINT FK_KHMO_HOCPHAN
FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANSU
FOREIGN KEY (MAGV) REFERENCES NHANSU(MANV);

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_KHMO
FOREIGN KEY (MAHP, HK, NAM, MACT) REFERENCES KHMO(MAHP, HK, NAM, MACT);

ALTER TABLE DANGKY
ADD CONSTRAINT FK_DANGKY_SINHVIEN
FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);

ALTER TABLE DANGKY
ADD CONSTRAINT FK_DANGKY_PHANCONG
FOREIGN KEY (MAGV, MAHP, HK, NAM, MACT) REFERENCES PHANCONG(MAGV, MAHP, HK, NAM, MACT);




----------View----------------
CREATE OR REPLACE VIEW UV_SINHVIEN_VIEW
AS
SELECT MASV, HOTEN, PHAI, MACT, MANGANH FROM SINHVIEN;

CREATE OR REPLACE VIEW UV_SINHVIEN_PERSONAL_VIEW
AS
SELECT * FROM SINHVIEN WHERE UPPER(MASV) = USER;


CREATE OR REPLACE VIEW UV_NHANSU_VIEW
AS
SELECT HOTEN, PHAI, NGSINH, DT, MADV FROM NHANSU;

CREATE OR REPLACE VIEW UV_NHANSU_PERSONAL_VIEW
AS
SELECT * FROM NHANSU WHERE UPPER(MANV) = USER;


CREATE OR REPLACE VIEW UV_KHMO_VIEW
AS
SELECT * FROM KHMO
WHERE MACT IN ( SELECT MACT FROM SINHVIEN WHERE UPPER(MASV) = USER );


CREATE OR REPLACE VIEW UV_DANGKY_VIEW
AS
SELECT * FROM DANGKY WHERE UPPER(MASV) = USER;


------ Create Role------

CREATE ROLE basic_employee_role;
CREATE ROLE lecturer_role;
CREATE ROLE academic_staff_role;
CREATE ROLE unit_head_role;
CREATE ROLE department_head_role;
CREATE ROLE student_role;


------- Create User --- 

CREATE USER SV01 IDENTIFIED BY sv01;
CREATE USER SV02 IDENTIFIED BY sv02;
CREATE USER SV03 IDENTIFIED BY sv03;

CREATE USER NV01 IDENTIFIED BY nv01;
CREATE USER NV02 IDENTIFIED BY nv02;
CREATE USER NV03 IDENTIFIED BY nv03;
CREATE USER NV04 IDENTIFIED BY nv04;
CREATE USER NV05 IDENTIFIED BY nv05;

GRANT CREATE SESSION TO SV01;
GRANT CREATE SESSION TO SV02;
GRANT CREATE SESSION TO SV03;

GRANT CREATE SESSION TO NV01;
GRANT CREATE SESSION TO NV02;
GRANT CREATE SESSION TO NV03;
GRANT CREATE SESSION TO NV04;
GRANT CREATE SESSION TO NV05;



-- grant mot so quyen de test giao dien
GRANT SELECT ON UV_SINHVIEN_VIEW TO student_role;
GRANT student_role TO SV01;

GRANT SELECT ON UV_NHANSU_VIEW TO basic_employee_role;
GRANT basic_employee_role TO NV01;

GRANT SELECT ON UV_NHANSU_PERSONAL_VIEW TO NV01;








