-- Dang nhap bang admin

CREATE TABLE NHANSU (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(10),
    NGSINH DATE,
    PHUCAP INT,
    DT VARCHAR2(10),
    VAITRO NVARCHAR2(20),
    MADV VARCHAR2(10)
);

CREATE TABLE SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(10),
    NGSINH DATE,
    DCHI NVARCHAR2(100),
    DT VARCHAR2(10),
    MACT VARCHAR2(10),
    MANGANH VARCHAR2(10),
    SOTCTL INT,
    DTBTL NUMBER
);

CREATE TABLE DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV NVARCHAR2(50),
    TRGDV VARCHAR2(10)
);

CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP NVARCHAR2(80),
    SOTC INT,
    STLT INT,
    STTH INT,
    SOSVTD INT,
    MADV VARCHAR2(10)
);


CREATE TABLE KHMO (
    MAHP VARCHAR2(10),
    HK INT,
    NAM INT,
    MACT VARCHAR2(10),
    PRIMARY KEY(MAHP, HK, NAM, MACT)
);


CREATE TABLE PHANCONG (
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK INT,
    NAM INT,
    MACT VARCHAR2(10),
    PRIMARY KEY(MAGV, MAHP, HK, NAM, MACT)
);


CREATE TABLE DANGKY (
    MASV VARCHAR2(10),
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK INT,
    NAM INT,
    MACT VARCHAR2(10),
    DIEMTH NUMBER, 
    DIEMQT NUMBER, 
    DIEMCK NUMBER,
    DIEMTK NUMBER,
    PRIMARY KEY(MASV, MAGV, MAHP, HK, NAM, MACT)
);


ALTER TABLE NHANSU
ADD CONSTRAINT FK_NHANSU_DONVI
FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

ALTER TABLE DONVI
ADD CONSTRAINT FK_DONVI_NHANSU
FOREIGN KEY (TRGDV) REFERENCES NHANSU(MANV);

ALTER TABLE HOCPHAN
ADD CONSTRAINT FK_HOCPHAN_DONVI
FOREIGN KEY (MADV) REFERENCES DONVI(MADV);

ALTER TABLE KHMO
ADD CONSTRAINT FK_KHMO_HOCPHAN
FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANSU
FOREIGN KEY (MAGV) REFERENCES NHANSU(MANV);

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_KHMO
FOREIGN KEY (MAHP, HK, NAM, MACT) REFERENCES KHMO(MAHP, HK, NAM, MACT);

ALTER TABLE DANGKY
ADD CONSTRAINT FK_DANGKY_SINHVIEN
FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);

ALTER TABLE DANGKY
ADD CONSTRAINT FK_DANGKY_PHANCONG
FOREIGN KEY (MAGV, MAHP, HK, NAM, MACT) REFERENCES PHANCONG(MAGV, MAHP, HK, NAM, MACT);
