-- Dang Nhap bang admin
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE ROLE RL_SINHVIEN;
CREATE ROLE RL_NHANVIENCOBAN;
CREATE ROLE RL_GIANGVIEN;
CREATE ROLE RL_GIAOVU;
CREATE ROLE RL_TRUONGDONVI;
