-- CS#1: Nguoi dung co VAITRO là “Nhân viên co ban” có quyen truy cap du lieu:
-- - Xem dòng du lieu cua chính mình trong quan he NHANSU, có the chinh sua so dien thoai (DT) cua chính mình (neu so dien thoai có thay doi).
-- - Xem thông tin cua tat ca SINHVIEN, DONVI, HOCPHAN, KHMO.
-- - Xem dòng du lieu cua chính mình trong quan he NHANSU
CREATE OR REPLACE VIEW NHANSU_NV_VIEW AS
SELECT * FROM ADMIN.NHANSU WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER') AND VAITRO = 'NHAN VIEN';

REVOKE SELECT ON ADMIN.NHANSU_NV_VIEW FROM RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.NHANSU_NV_VIEW TO RL_NHANVIENCOBAN;
SELECT * FROM ADMIN.NHANSU_NV_VIEW;

SELECT * 
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'NV101';

SELECT * 
FROM DBA_SYS_ROLE
WHERE GRANTEE = 'NV101';

-- Tao trigger cho UPDATE(DT) tren view NHANSU_NV_VIEW
CREATE OR REPLACE TRIGGER TRIGGER_NHANSU_NV_UPDATE
INSTEAD OF UPDATE
ON ADMIN.NHANSU_NV_VIEW
FOR EACH ROW
DECLARE
  v_already_fired NUMBER;
BEGIN
  -- Xem trigger duoc kich hoat chua
  SELECT COUNT(*) INTO v_already_fired
  FROM user_triggers
  WHERE trigger_name = 'TRIGGER_NHANSU_NV_UPDATE'
  AND status = 'ENABLED'
  AND triggering_event = 'UPDATE';

  -- Neu trigger chua duoc kich hoat thi update
  IF v_already_fired = 0 THEN
    UPDATE ADMIN.NHANSU_NV_VIEW
    SET DT = :NEW.DT
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
  END IF;
END;

-- Trao quyen UPDATE(DT) cho RL_NHANVIENCOBAN
REVOKE UPDATE ON ADMIN.NHANSU_NV_VIEW FROM RL_NHANVIENCOBAN;
GRANT UPDATE(DT) ON ADMIN.NHANSU_NV_VIEW TO RL_NHANVIENCOBAN;
UPDATE ADMIN.NHANSU_NV_VIEW SET DT = '0941499767';

-- Trao quyen SELECT tren cac bang SINHVIEN, DONVI, HOCPHAN, KHMO.
-- - Xem thông tin cua tat ca SINHVIEN, DONVI, HOCPHAN, KHMO.
GRANT SELECT ON ADMIN.SINHVIEN TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.DONVI TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.HOCPHAN TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.KHMO TO RL_NHANVIENCOBAN;