-- CS#1: Nguoi dung co VAITRO l� �Nh�n vi�n co ban� c� quyen truy cap du lieu:
-- - Xem d�ng du lieu cua ch�nh m�nh trong quan he NHANSU, c� the chinh sua so dien thoai (DT) cua ch�nh m�nh (neu so dien thoai c� thay doi).
-- - Xem th�ng tin cua tat ca SINHVIEN, DONVI, HOCPHAN, KHMO.
-- - Xem d�ng du lieu cua ch�nh m�nh trong quan he NHANSU
CREATE OR REPLACE VIEW UV_CANHAN_NHANSU AS
SELECT * FROM ADMIN.NHANSU WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

-- Tao trigger cho UPDATE(DT) tren view UV_CANHAN_NHANSU
CREATE OR REPLACE TRIGGER UTR_UPDATE_DIENTHOAI_NHANSU
INSTEAD OF UPDATE
ON ADMIN.UV_CANHAN_NHANSU
FOR EACH ROW
BEGIN
    update ADMIN.NHANSU set DT = :NEW.DT where upper(MANV) = SYS_CONTEXT('USERENV', 'SESSION_USER');
END;

-- Trao quyen SELECT, UPDATE(DT) cho RL_NHANVIENCOBAN
GRANT SELECT, UPDATE(DT) ON ADMIN.UV_CANHAN_NHANSU TO RL_NHANVIENCOBAN;

-- Trao quyen SELECT tren cac bang SINHVIEN, DONVI, HOCPHAN, KHMO.
-- - Xem th�ng tin cua tat ca SINHVIEN, DONVI, HOCPHAN, KHMO.
GRANT SELECT ON ADMIN.SINHVIEN TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.DONVI TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.HOCPHAN TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.KHMO TO RL_NHANVIENCOBAN;
