-- CS#1: Nguoi dung co VAITRO là “Nhân viên co ban” có quyen truy cap du lieu:
-- - Xem dòng du lieu cua chính mình trong quan he NHANSU, có the chinh sua so dien thoai (DT) cua chính mình (neu so dien thoai có thay doi).
-- - Xem thông tin cua tat ca SINHVIEN, DONVI, HOCPHAN, KHMO.
-- - Xem dòng du lieu cua chính mình trong quan he NHANSU
CREATE OR REPLACE VIEW UV_CANHAN_NHANSU AS
SELECT * FROM ADMIN.NHANSU WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

-- Tao trigger cho UPDATE(DT) tren view UV_CANHAN_NHANSU
CREATE OR REPLACE TRIGGER UTR_UPDATE_DIENTHOAI_NHANSU
INSTEAD OF UPDATE
ON ADMIN.UV_CANHAN_NHANSU
FOR EACH ROW
BEGIN
    update ADMIN.NHANSU set DT = :NEW.DT where upper(MANV) = SYS_CONTEXT('USERENV', 'SESSION_USER');
END;

-- Trao quyen SELECT, UPDATE(DT) cho RL_NHANVIENCOBAN
GRANT SELECT, UPDATE(DT) ON ADMIN.UV_CANHAN_NHANSU TO RL_NHANVIENCOBAN;

-- Trao quyen SELECT tren cac bang SINHVIEN, DONVI, HOCPHAN, KHMO.
-- - Xem thông tin cua tat ca SINHVIEN, DONVI, HOCPHAN, KHMO.
GRANT SELECT ON ADMIN.SINHVIEN TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.DONVI TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.HOCPHAN TO RL_NHANVIENCOBAN;
GRANT SELECT ON ADMIN.KHMO TO RL_NHANVIENCOBAN;
