-- dang nhap bang sys
SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security'; 
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS'; 

EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

SHUTDOWN IMMEDIATE; 
STARTUP; 

select * from v$services;

ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;

-- open PDBQLHT
ALTER PLUGGABLE DATABASE PDBQLHT OPEN READ WRITE;

ALTER SESSION SET CONTAINER= PDBQLHT; 
SHOW CON_NAME;



-- tao admin
CREATE USER ADMIN IDENTIFIED BY 1234 CONTAINER = CURRENT; 
GRANT DBA TO ADMIN;
GRANT CONNECT, RESOURCE TO ADMIN;
GRANT UNLIMITED TABLESPACE TO ADMIN;
GRANT SELECT ANY DICTIONARY TO ADMIN;
GRANT CREATE USER TO admin;
GRANT CONNECT TO admin WITH ADMIN OPTION;
grant create session to admin with admin option;
-- cap quyen execcute
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_user_admin TO ADMIN WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_label_admin TO ADMIN WITH GRANT OPTION; 
GRANT EXECUTE ON sa_policy_admin TO ADMIN WITH GRANT OPTION; 
GRANT EXECUTE ON char_to_label TO ADMIN WITH GRANT OPTION; 
GRANT EXECUTE ON sa_audit_admin  TO ADMIN WITH GRANT OPTION;
GRANT EXECUTE ON label_to_char TO ADMIN WITH GRANT OPTION; 
-- ADD ADMIN_OLS vao LBAC_DBA 
GRANT LBAC_DBA TO ADMIN; 
GRANT EXECUTE ON sa_sysdba TO ADMIN; 
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN;



-- SAU KHI CHAY B2 BEN OLS_ADMIN_OLS THI CHAY CAI NAY DE CHECK
SELECT * FROM DBA_SA_LEVELS;
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS;
SELECT * FROM DBA_SA_GROUP_HIERARCHY; 


