-- Dang nhap bang admin vao PDBQLHT

--B1: tao policy
BEGIN 
    SA_SYSDBA.CREATE_POLICY( 
    policy_name => 'ols_policy', 
    column_name => 'ols_label'
); 
END; 
--BEGIN 
--    SA_SYSDBA.DROP_POLICY( 
--    policy_name => 'region_policy'
--); 
--END; 

EXEC SA_SYSDBA.ENABLE_POLICY ('ols_policy'); 

-- cap role quan ly ols_policy cho admin
grant ols_policy_dba to ADMIN;
set role all;
--select* from session_roles;


-- B2
--TAO COMPONENT CUA LABEL 
--->TAO LEVEL 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('ols_policy',900,'TK','TRUONG KHOA');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('ols_policy',800,'TDV','TRUONG DON VI');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('ols_policy',700,'GV','GIANG VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('ols_policy',600,'GVU','GIAO VU');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('ols_policy',500,'NV','NHAN VIEN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('ols_policy',400,'SV','SINH VIEN');

--->TAO COMPARTMENT 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('ols_policy',100,'HTTT','HE THONG THONG TIN');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('ols_policy',200,'CNPM','CONG NGHE PHAN MEM');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('ols_policy',300,'KHMT','KHOA HOC MAY TINH');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('ols_policy',400,'CNTT','CONG NGHE TRI THUC');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('ols_policy',500,'TGMT','THI GIAC MAY TINH');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('ols_policy',600,'MMT','MANG MAY TINH');
--->TAO GROUP 
EXECUTE SA_COMPONENTS.CREATE_GROUP('ols_policy',100,'CS1','CO SO 1'); 
EXECUTE SA_COMPONENTS.CREATE_GROUP('ols_policy',200,'CS2','CO SO 2'); 



-- B3: tao bang THONG BAO
CREATE TABLE THONGBAO 
( 
    ID INT PRIMARY KEY,
    NOIDUNG NVARCHAR2(200)
);

INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(1,N'Thông báo dành cho Trưởng khoa');
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(2,N'Thông báo dành cho Trưởng bộ môn không phân biệt vị trí địa lý');
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(3,N'Thông báo dành cho Giáo vụ'); 
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(4,N'Thông báo dành cho tất cả các Trưởng đơn vị'); 
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(5,N'Thông báo dành cho Sinh viên ngành HTTT ở CS1'); 
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(6,N'Thông báo dành cho Trưởng bộ môn KHMT ở CS1'); 
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(7,N'Thông báo dành cho Trưởng bộ môn KHMT ở CS1 và CS2'); 
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(8,N'Thông báo dành cho Giảng viên bộ môn HTTT ở CS1'); 
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(9,N'Thông báo dành cho tất cả Nhân viên ở CS1'); 
INSERT INTO THONGBAO(ID, NOIDUNG) VALUES(10,N'Thông báo dành cho Sinh viên ngành CNPM ở CS1 và CS2'); 

SELECT * FROM THONGBAO; 

-- grant quyen select thong bao
GRANT SELECT ON THONGBAO TO RL_SINHVIEN;
GRANT SELECT ON THONGBAO TO RL_NHANVIENCOBAN;
-- BEGIN
--     FOR emp IN (SELECT MANV FROM NHANSU) LOOP
--         EXECUTE IMMEDIATE 'GRANT SELECT ON THONGBAO TO ' || emp.MANV;
--     END LOOP;
--     FOR student IN (SELECT MASV FROM SINHVIEN) LOOP
--         EXECUTE IMMEDIATE 'GRANT SELECT ON THONGBAO TO ' || student.MASV;
--     END LOOP;
-- END;


--Them truong co so vao bang NHANSU va NHANVIEN
ALTER TABLE NHANSU ADD COSO VARCHAR2(10);
ALTER TABLE SINHVIEN ADD COSO VARCHAR2(10);

UPDATE SINHVIEN SET COSO = 'CS1' WHERE MACT <> 'CQ';
UPDATE SINHVIEN SET COSO = 'CS2' WHERE MACT = 'CQ';

UPDATE NHANSU SET COSO = 'CS1,CS2' WHERE VAITRO = 'TRUONG KHOA' OR VAITRO = 'TRUONG DON VI';
UPDATE NHANSU SET COSO = 'CS1' 
WHERE MANV IN ('NV101', 'NV102', 'NV103', 'NV201', 'NV202', 'NV203',
            'NV301', 'NV302', 'NV303', 'NV306', 'NV307', 'NV308', 
            'NV311', 'NV312', 'NV313', 'NV316', 'NV317', 'NV318',
            'NV321', 'NV322', 'NV323', 'NV326', 'NV327', 'NV328');
UPDATE NHANSU SET COSO = 'CS2' 
WHERE MANV IN ('NV104', 'NV105', 'NV204', 'NV205', 'NV304', 'NV305',  'NV309', 'NV310', 'NV314', 'NV315', 'NV319', 'NV320', 'NV324', 'NV325', 'NV329', 'NV330');
-- CHECK COSO
SELECT* FROM SINHVIEN;
SELECT* FROM NHANSU;



-- B4 TAO NHAN cho du lieu
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 9000, 'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2');

EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 8000, 'TDV');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 8001, 'TDV::CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 8002, 'TDV:KHMT:CS1,CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 8100, 'TDV:KHMT:CS1');

EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 7000, 'GV');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 7100, 'GV:HTTT:CS1');

EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 6000, 'GVU');

EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 5000, 'NV');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 5100, 'NV::CS1');

EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 4000, 'SV');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 4001, 'SV:CNPM:CS1,CS2'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('ols_policy', 4100, 'SV:HTTT:CS1'); 

--KIEM TRA NHAN DA TAO
select* from all_sa_labels;



-- B5: APPLY NO CONTROL
BEGIN 
 SA_POLICY_ADMIN.APPLY_TABLE_POLICY ( 
    POLICY_NAME => 'OLS_POLICY',
    SCHEMA_NAME => 'ADMIN', 
    TABLE_NAME => 'THONGBAO',
    TABLE_OPTIONS => 'NO_CONTROL'
 ); 
END;



--B6: GAN NHAN CHO THONG BAO
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2') 
WHERE ID = 1;
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','TDV::CS1,CS2') 
WHERE ID = 2;
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','GVU') 
WHERE ID = 3;

-- d) gan nhan cho t1 de t1 duoc phat tan (doc) boi tat ca cac truong don vi
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','TDV') 
WHERE ID = 4;
-- e) gan nhan cho t2 de phat tan t2 den sinh vien thuoc nganh HTT o CS1
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','SV:HTTT:CS1') 
WHERE ID = 5;
-- f) gan nhan cho t3 de phat tan t3 den truong bo mon KHMT o CS1
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','TDV:KHMT:CS1') 
WHERE ID = 6;
-- g) gan nhan cho t4 de phat tan t4 den truong bo mon KHMT o CS1 va CS2
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','TDV:KHMT:CS1,CS2') 
WHERE ID = 7;
-- h) Them 3 chinh sach phat tan
-- phat tan dong du lieu t5 den cac Giang vien thuoc bo mon HTTT o CS1
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','GV:HTTT:CS1') 
WHERE ID = 8;
-- phat tan dong du lieu t6 den Tat ca Nhan vien o CS1
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','NV::CS1') 
WHERE ID = 9;
-- phat tan dong du lieu t7 den Sinh vien nganh CNPM o CS1 va CS2
UPDATE THONGBAO 
SET OLS_LABEL = CHAR_TO_LABEL('OLS_POLICY','SV:CNPM:CS1,CS2') 
WHERE ID = 10;


SELECT * FROM THONGBAO;


--B7: AP DUNG OLS VAO BANG 
BEGIN 
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('OLS_POLICY','ADMIN','THONGBAO');
SA_POLICY_ADMIN.APPLY_TABLE_POLICY ( 
    policy_name => 'OLS_POLICY', 
    schema_name => 'ADMIN', 
    table_name => 'THONGBAO',
    table_options => 'READ_CONTROL',
    predicate => null
); 
END; 


-- B8: gan label cho user
BEGIN
    FOR emp IN (SELECT * FROM NHANSU) LOOP
        if emp.VAITRO = 'TRUONG KHOA' then
            SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY',emp.MANV,'TK:HTTT,CNPM,KHMT,CNTT,TGMT,MMT:CS1,CS2'); 
        elsif emp.VAITRO = 'TRUONG DON VI' then
            SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY',emp.MANV,'TDV:' || emp.MADV || ':CS1,CS2');
        elsif  emp.VAITRO = 'NHAN VIEN' then
            SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY',emp.MANV,'NV::' || emp.COSO);
        elsif  emp.VAITRO = 'GIAO VU' then
            SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY',emp.MANV,'GVU::' || emp.COSO);
        elsif  emp.VAITRO = 'GIANG VIEN' then
            SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY',emp.MANV,'GV:' || emp.MADV || ':' || emp.COSO);
        end if;
    END LOOP;
    FOR student IN (SELECT * FROM SINHVIEN) LOOP
        SA_USER_ADMIN.SET_USER_LABELS('OLS_POLICY',student.MASV,'SV:' || student.MANGANH || ':' || student.COSO);
    END LOOP;
end;



-- kiem tra label cua nguoi dung
select* from dba_sa_user_labels;






