-- dang nhap bang sys
SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security'; 
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS'; 

EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

SHUTDOWN IMMEDIATE; 
STARTUP; 

select * from v$services;

ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;

-- open PDBQLHT
ALTER PLUGGABLE DATABASE PDBQLHT OPEN READ WRITE;

ALTER SESSION SET CONTAINER= PDBQLHT; 
SHOW CON_NAME;

-- tao admin_ols
CREATE USER ADMIN_OLS IDENTIFIED BY 1234 CONTAINER = CURRENT; 
GRANT CONNECT, RESOURCE TO ADMIN_OLS;
GRANT UNLIMITED TABLESPACE TO ADMIN_OLS;
GRANT SELECT ANY DICTIONARY TO ADMIN_OLS;
-- cap quyen execcute
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_user_admin TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_label_admin TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_policy_admin TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON char_to_label TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_audit_admin  TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON label_to_char TO ADMIN_OLS WITH GRANT OPTION; 
-- ADD ADMIN_OLS vao LBAC_DBA 
GRANT LBAC_DBA TO ADMIN_OLS; 
GRANT EXECUTE ON sa_sysdba TO ADMIN_OLS; 
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN_OLS;



-- SAU KHI CHAY B2 BEN OLS_ADMIN_OLS THI CHAY CAI NAY DE CHECK
SELECT * FROM DBA_SA_LEVELS;
SELECT * FROM DBA_SA_COMPARTMENTS;
SELECT * FROM DBA_SA_GROUPS;
SELECT * FROM DBA_SA_GROUP_HIERARCHY; 


-- B8: Tao user o PDBQLHT
CREATE USER TruongKhoa IDENTIFIED BY 1234;
CREATE USER GiaoVu IDENTIFIED BY 1234;
CREATE USER TBM_CS2 IDENTIFIED BY 1234;
CREATE USER TruongDonVi IDENTIFIED BY 1234;
CREATE USER SV_HTTT_CS1 IDENTIFIED BY 1234;
CREATE USER TBM_KHMT_CS1 IDENTIFIED BY 1234;
CREATE USER TBM_KHMT_CS1_CS2 IDENTIFIED BY 1234;


-- B9: grant quyen
GRANT CONNECT TO TruongKhoa, GiaoVu, TBM_CS2, TruongDonVi, SV_HTTT_CS1,TBM_KHMT_CS1, TBM_KHMT_CS1_CS2; 
GRANT SELECT ON ADMIN_OLS.THONGBAO TO TruongKhoa, GiaoVu, TBM_CS2, TruongDonVi, SV_HTTT_CS1,TBM_KHMT_CS1, TBM_KHMT_CS1_CS2; 

