@echo off
(
echo RUN {
echo  ALTER  PLUGGABLE DATABASE PDBQLHT CLOSE;
echo  RESTORE PLUGGABLE DATABASE PDBQLHT;
echo  RECOVER  PLUGGABLE DATABASE PDBQLHT;
echo  ALTER PLUGGABLE DATABASE PDBQLHT OPEN;
echo }
echo EXIT;
) | rman target /

pause
