@echo off
(
echo RUN {
echo  ALTER  PLUGGABLE DATABASE ATBM_CQ_07 CLOSE;
echo  RESTORE PLUGGABLE DATABASE ATBM_CQ_07;
echo  RECOVER  PLUGGABLE DATABASE ATBM_CQ_07;
echo  ALTER PLUGGABLE DATABASE ATBM_CQ_07 OPEN;
echo }
echo EXIT;
) | rman target /

pause
